/* ============================================================
   Proyecto Final - BI para decisiones estrategicas
   Dominio: Bodega / Inventario y pedidos
   Script: DDL
   ============================================================ */

/* Ejecutar estos DROP solo si las tablas ya existen.

DROP TABLE bd_detalle_pedido CASCADE CONSTRAINTS;
DROP TABLE bd_pedidos CASCADE CONSTRAINTS;
DROP TABLE bd_productos CASCADE CONSTRAINTS;
DROP TABLE bd_clientes CASCADE CONSTRAINTS;
DROP TABLE bd_proveedores CASCADE CONSTRAINTS;

*/

CREATE TABLE bd_proveedores (
    proveedor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nit          VARCHAR2(20) NOT NULL,
    nombre       VARCHAR2(60) NOT NULL,
    telefono     VARCHAR2(20),
    email        VARCHAR2(60),
    estado       VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    -- Constraints
    CONSTRAINT pk_bd_proveedores PRIMARY KEY (proveedor_id),
    CONSTRAINT uq_bd_proveedores_nit UNIQUE (nit),
    CONSTRAINT ck_bd_proveedores_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE bd_clientes (
    cliente_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento VARCHAR2(5) NOT NULL,
    num_documento  VARCHAR2(20) NOT NULL,
    nombre         VARCHAR2(60) NOT NULL,
    email          VARCHAR2(60),
    estado         VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    -- Constraints
    CONSTRAINT pk_bd_clientes PRIMARY KEY (cliente_id),
    CONSTRAINT uq_bd_clientes_doc UNIQUE (tipo_documento, num_documento),
    CONSTRAINT ck_bd_clientes_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE bd_productos (
    producto_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    proveedor_id    NUMBER NOT NULL,
    codigo_producto VARCHAR2(20) NOT NULL,
    nombre          VARCHAR2(60) NOT NULL,
    categoria       VARCHAR2(30) NOT NULL,
    precio_unitario NUMBER(12,2) NOT NULL,
    stock_actual    NUMBER NOT NULL,
    stock_minimo    NUMBER NOT NULL,
    estado          VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,

    -- Constraints
    CONSTRAINT pk_bd_productos PRIMARY KEY (producto_id),
    CONSTRAINT fk_bd_prod_proveedor FOREIGN KEY (proveedor_id) REFERENCES bd_proveedores(proveedor_id),
    CONSTRAINT uq_bd_productos_codigo UNIQUE (codigo_producto),
    CONSTRAINT ck_bd_prod_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_bd_prod_stock_actual CHECK (stock_actual >= 0),
    CONSTRAINT ck_bd_prod_stock_minimo CHECK (stock_minimo >= 0),
    CONSTRAINT ck_bd_productos_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE bd_pedidos (
    pedido_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    num_pedido   VARCHAR2(20) NOT NULL,
    cliente_id   NUMBER NOT NULL,
    fecha_pedido DATE DEFAULT SYSDATE NOT NULL,
    estado       VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    observacion  VARCHAR2(120),

    -- Constraints
    CONSTRAINT pk_bd_pedidos PRIMARY KEY (pedido_id),
    CONSTRAINT uq_bd_pedidos_num UNIQUE (num_pedido),
    CONSTRAINT fk_bd_ped_cliente FOREIGN KEY (cliente_id) REFERENCES bd_clientes(cliente_id),
    CONSTRAINT ck_bd_pedidos_estado CHECK (estado IN ('PENDIENTE', 'DESPACHADO', 'CANCELADO'))
);

CREATE TABLE bd_detalle_pedido (
    detalle_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pedido_id       NUMBER NOT NULL,
    producto_id     NUMBER NOT NULL,
    cantidad        NUMBER NOT NULL,
    precio_unitario NUMBER(12,2) NOT NULL,

    -- Constraints
    CONSTRAINT pk_bd_detalle_pedido PRIMARY KEY (detalle_id),
    CONSTRAINT fk_bd_det_pedido FOREIGN KEY (pedido_id) REFERENCES bd_pedidos(pedido_id),
    CONSTRAINT fk_bd_det_producto FOREIGN KEY (producto_id) REFERENCES bd_productos(producto_id),
    CONSTRAINT uq_bd_det_ped_prod UNIQUE (pedido_id, producto_id),
    CONSTRAINT ck_bd_det_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_bd_det_precio CHECK (precio_unitario >= 0)
);

COMMIT;
